### ISSUE TITLE
allow to retrieve the model of a ts_t

### ISSUE THREAD

**Issue by adl** [ticktac-project/tchecker#12]
After I have done
```
typedef tchecker::zg::ta::elapsed_extraLUplus_local_t zone_graph_t;
tchecker::zg::ta::model_t model(*sysdecl, log);
zone_graph_t::ts_t ts(model);
```
I'm currently writing a wrapper so that the `ts` can be seen as a Kripke structure by Spot.  So my class hold a reference to `ts`.

I clearly need `ts` to explore the graph, but apparently I also need `model` to dissect the states (let's say for now that I just want to print them).  Would it be possible to add a `model()` method to `ts` so that I can retrieve the model from `ts` without having to store an additional reference?

**Comment by fredher** [comment]
I have made the modification to all transition systems as well as finite state machines, timed automata, zone graphs, etc. However, I have not modified `tchecker::ts::ts_t` as I don't feel the need to constrain this interface to provide a `model()` method. I am assuming that your wrapper takes a `TS` template parameter. If it is not the case, let me know, I will update the `tchecker::ts::ts_t` interface (although I would prefer not to).

**Comment by adl** [comment]
Thanks, `tchecker::zg::ta::elapsed_extraLUplus_local_t::ts_t::model()` is all I use currently.  I'll add templates later, once I get this working.
