### ISSUE TITLE
Simplify graph display

### ISSUE THREAD

**Issue by fredher** [ticktac-project/tchecker#32]
Output graphs using a fixed format: nodes and edges, with attributes (free list of attributes). Then, implement tools to translate this format into DOT or other formats

**Comment by adl** [comment]
Have you considered using the dot format directly?  The dot format allows you to add arbitrary attributes to nodes and edges (you could use a custom prefix to avoid clashes with GraphViz's currently used attributes), and the tool `gvpr` (from GraphViz) can be used to alter the graph based on those attributes, producing another dot graph, some statistics, or even a completely different syntax.

**Comment by fredher** [comment]
Yes that's almost surely what I will do. Sorry if my message was unclear. What I meant is: implement a single output format. And build other tools to translate from this output format to other format of interest.

**Comment by fredher** [comment]
Solved in v0.3
