### ISSUE TITLE
Problem with lu_map_capacity

### ISSUE THREAD

**Issue by schlepil** [ticktac-project/tchecker#34]
Hi everyone,

when trying to copy create a transition system (elapsed/local_lu) i encountered some problems:

First when trying to do
ts_t ts2 = ts;
There is a compiler error. The compiler tries to use the template constructor (tchecker/zg/details/ts.hh line 52) instead of using the correct one (line 61). This can be fixed by making the template constructor explicit.

Then another problem appears: The capacity of the array in the local_lu_map is not correctly set. That is in the model the (tchecker::zg::ta::model_t) the capacity is correct, once the transition system constructed (ts_t ts(model)), the capacity takes on random(?) values. This causes then segmentation faults when invoking to copy constructor on ts.

An archive with an simply example (src/tchecker/test_cpy.cc) can be downloaded
[here](https://cloud.lrde.epita.fr/index.php/s/pLMX6AwsHq32FRg)
where the problem is detailed in the comments. Simply run it on the examples in "bug_examples" which are just the tchecker files for corsso and csmacd with argument 5.

Have a nice day everyone,
Philipp

**Comment by fredher** [comment]
Hi Philipp,

There was a huge bug in copy constructors of extrapolations: `_L[i] instead of (*_L)[i]`. I have checked your code `test_cpy.cc` with the last committed version of TChecker, and it works fine.

Thanks, best regards,
Frédéric

**Comment by schlepil** [comment]
Salut!

Merci de l'avoir corrigé! J'ai cherché un peu aussi, mais je n'ai pas
trouvé...
Je vais tester avec mon program plus complet plus tard.

Bonne journée encore,
Philipp

Am Mo., 7. Okt. 2019 um 10:14 Uhr schrieb Frédéric Herbreteau <
notifications@github.com>:

**Comment by schlepil** [comment]
Resalut!

J'ai trouvé un autre bug, et j'ai fait un issue et pull-rquest associé.

est-ce que t'as un bon article sous la main qui explique les offset-dbm?
Comme ca je pourrai faire un fix pour ca aussi, mais je comprends pas assez
bien ce que se passe pour le moment.

Bonne journée et a+
Philipp

Am Mo., 7. Okt. 2019 um 10:14 Uhr schrieb Frédéric Herbreteau <
notifications@github.com>:
