### ISSUE TITLE
Multilines attributes

### ISSUE THREAD

**Issue by pictavien** [ticktac-project/tchecker#39]
Hi,

The parser for system descriptions does not allow values of attributes written on several lines. 
Would it create an issue if we allow newlines (i.e. allows '\n' in TOK_TEXT in system.ll) ?

**Comment by fredher** [comment]
Hi,

The only potential problem I see is in system.ll, line 121:
```
[\n]+          { loc.lines(static_cast<int>(spyyleng)); loc.step(); }
[^:{}#\n]*     { return system::parser_t::make_TOK_TEXT(spyytext, loc); }
```
We need to increment the line number each time we see a `\n`. I believe it still works if we remove `\n` from the anti-pattern of TOK_TEXT. Token `TOK_TEXT` is only used for attribute values, so we can modify the lines above without impacting the lexer and the parser.

**Comment by pictavien** [comment]
Ok. Thanks.
