### ISSUE TITLE
let garabage collection be robust to allocator destruction

### ISSUE THREAD

**Issue by adl** [ticktac-project/tchecker#40]
Currently allocators do not "unregister" from the garbage collector.  That means the GC must be stopped before any allocator is destroyed, causing issues such as #11.  It also makes hard to build Python bindings, were you have little control on the destruction time.

It seems that having the allocators to unregister from the GC (and wait until their collecting function in not running anymore) when they are destroyed could solve these issues.

**Comment by fredher** [comment]
Concurrent GC removed in v0.3
