### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by alfredost** [ticktac-project/tchecker#48]
Hey, I've been following [this](https://github.com/ticktac-project/tchecker/wiki/Implementing-a-reachability-algorithm-using-TChecker-libraries) guide to implement a reachability algorithm on Ubuntu 21.10. More specifically, in the 'Before we start' section, after `cmake` has succeeded, when I run the `make` command from the `build` directory, I get this error:

```
[  8%] Linking CXX executable reach-4
during IPA pass: icf
lto1: internal compiler error: Errore di segmentazione
0x9db587 crash_signal
  ../../src/gcc/toplev.c:327
0x7f755c10c51f ???
  ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
0x1297c16 varpool_node::get_constructor()
  ../../src/gcc/varpool.c:300
0x1297c16 varpool_node::get_constructor()
  ../../src/gcc/varpool.c:279
0x694f55 ipa_icf::sem_variable::equals(ipa_icf::sem_item*, hash_map<symtab_node*, ipa_icf::sem_item*, simple_hashmap_traits<default_hash_traits<symtab_node*>, ipa_icf::sem_item*> >&)
  ../../src/gcc/ipa-icf.c:1697
0xe9c4ca ipa_icf::sem_item_optimizer::subdivide_classes_by_equality(bool)
  ../../src/gcc/ipa-icf.c:2732
0x12a95bb ipa_icf::sem_item_optimizer::execute()
  ../../src/gcc/ipa-icf.c:2464
0x12a937b ipa_icf_driver
  ../../src/gcc/ipa-icf.c:3600
0x12a937b ipa_icf::pass_ipa_icf::execute(function*)
  ../../src/gcc/ipa-icf.c:3647
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See file:///usr/share/doc/gcc-11/README.Bugs for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/reach-4.dir/build.make:104: reach-4] Errore 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/reach-4.dir/all] Errore 2
make: *** [Makefile:103: all] Errore 2
```

Does anybody else get a segmentation fault when compiling the code?

**Comment by fredher** [comment]
Dear @alfredost 
This looks very similar to [https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102067](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102067).
Could you please try to build without -flto (remove -flto in line 17 of src/CMakeLists.txt)? You need to re-run cmake one the file has been modified.
Best regards,
Frédéric

**Comment by fredher** [comment]
I have not been able to reproduce the bug compiling TChecker on Ubuntu 21.10 with g++ 11.2.0 (and any other versions I have tried). I am closing the bug, and I hope that it is not an issue anymore.
