### ISSUE TITLE
No warning when the initial state set is empty

### ISSUE THREAD

**Issue by osankur** [ticktac-project/tchecker#49]
The tck-reach tool does not display any warning when the set of initial states is empty, e.g. when one forgets the initial: attribute, or writes it with a typo. It would be useful to add a warning.
It would also be useful to have warnings about ignored attributes which can help detect typos.

**Comment by fredher** [comment]
Closed by commits 0f5845e07084a563c3a53a5bdb902385313a9d5d and 504bcae10865c7db8f3c618ca424aad246b7c850
tck-reach issues a warning when a process has no initial location
tck-syntax does a better job: it outputs warning messages for all processes that do not have initial locations, as well as all unknown attributes
