### ISSUE TITLE
A compiling bug

### ISSUE THREAD

**Issue by rgu01** [ticktac-project/tchecker#51]
When compiling the project by using "make -j" and building the project in Netbeans (gcc), I got the following errors:

/usr/bin/ld: cannot open output file tck-reach: Is a directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot open output file tck-syntax: Is a directory
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot open output file tck-simulate: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/tck-reach.dir/build.make:130: src/tck-reach] Error 1
make[1]: *** [CMakeFiles/Makefile2:806: src/CMakeFiles/tck-reach.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/tck-syntax.dir/build.make:100: src/tck-syntax] Error 1
make[2]: *** [src/CMakeFiles/tck-simulate.dir/build.make:115: src/tck-simulate] Error 1
make[1]: *** [CMakeFiles/Makefile2:779: src/CMakeFiles/tck-syntax.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:752: src/CMakeFiles/tck-simulate.dir/all] Error 2
/usr/bin/ld: cannot open output file tck-liveness: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/tck-liveness.dir/build.make:115: src/tck-liveness] Error 1
make[1]: *** [CMakeFiles/Makefile2:833: src/CMakeFiles/tck-liveness.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Can you please tell me where I did wrong? Thank you.

**Comment by pictavien** [comment]
Hi Rong,

Where did you generate your Makefiles with the cmake command ? It seems that the compilation process clashes with some
source directories (e.g src/tck-reach). Usually we compile the project in a directory separated from the source tree as suggested in the README.

**Comment by rgu01** [comment]
Hi,

Thank you for your quick response. I ran the following commands in the folder of checker:

cmake ../tchecker -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/ron/tchecker/build
make -j

But it seems the build folder stays empty. What should I do?

**Comment by pictavien** [comment]
I assume that /home/ron/tchecker/ is your clone of the project. 
First, if you didn't change anything in your version of the project, you could clean up the repo `git clone -fdx` or restart with a fresh clone. Then,
```
cd /home/ron/tchecker
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/ron/tchecker/build/inst
make -j
```
If you then `make install`, the binaries should be copied in `/home/ron/tchecker/build/inst`.

**Comment by rgu01** [comment]
Thanks a lot. That went well both in my terminal and Netbeans. I will close this issue and probably come back to this panel when meeting new obstacles.
