### ISSUE TITLE
Can I use `tck-reach` to get the path in the automaton that witnesses reachability? 

### ISSUE THREAD

**Issue by Agnishom** [ticktac-project/tchecker#56]
In the "release" version of `tck-reach` that I downloaded, the help message tells me about the following way to extract certificates.

```
-C out_file   output a certificate (as a graph) in out_file
```

Is it possible to ask the tool to provide the path to the state we want?

For example, consider

```
system:simple

clock:1:x

event:a
event:b
event:c

process:P
location:P:l0{initial:}
location:P:l1{labels: green}
edge:P:l0:l0:a{}
edge:P:l0:l1:b{provided: x>1}
edge:P:l1:l1:c{}
```

Can I get the tool to print the timed word that takes me to location `l1`?

The command I have found so far is `./tck-reach -a reach -l green -C cert.txt ../examples/simple.txt` but it gives me a graph in this case instead of the timed word.

**Comment by fredher** [comment]
Dear Agnishom,
The latest version of TChecker (v0.6) can provide a symbolic path that witnesses reachability (please, run `tck-reach -h` for documentation).
The next release will also provide a concrete witness path, from which it is easy to compute the timed word. We expect this release to come soon.
Best regards,
Frédéric

**Comment by fredher** [comment]
Dear Agnishom,
The latest release of TChecker (v0.7) now includes concrete counter-examples generation (i.e. witness path with clock values and delays). See wiki for documentation.
Best regards,
Frédéric

**Comment by Agnishom** [comment]
Thank you for keeping me updated. I will check out the new release.
