### ISSUE TITLE
Using non-integer values in clock constraints?

### ISSUE THREAD

**Issue by Agnishom** [ticktac-project/tchecker#57]
I am curious if it is possible to have guards that look like this? `edge:P:l0:l1:b{provided: x>1.2}` 

Currently, it seems that this is rejected by the tool saying `ERROR: 1.4 Invalid character: .`

I have observed that in the Timed Automata Literature, it is usually assumed that the constraints are natural numbers, since it helps in ensuring that the region equivalence relation is finitary. The popular solution for dealing with rationals seems to be "multiplying out the denominators". I wonder if this has been implemented as a part of the TChecker tool and if it would make performance worse in practice.

Thanks

**Comment by fredher** [comment]
Dear Agnishom,
TChecker only supports natural numbers. We do not plan to support rational numbers or floating point numbers in the future. This would make the tool less efficient (representing a rational number requires more memory and operations than a natural number). Adding more complexity to the tool works against its efficiency.
Best regards,
Frédéric Herbreteau
