### ISSUE TITLE
Create db with INF_VALUE

### ISSUE THREAD

**Issue by Schulzen** [ticktac-project/tchecker#61]
Hi,

```
inline tchecker::dbm::db_t db(enum tchecker::ineq_cmp_t cmp, tchecker::integer_t value)

    {

      if ((value < tchecker::dbm::MIN_VALUE) || (value > tchecker::dbm::MAX_VALUE))

        throw std::invalid_argument("value out of bounds");

      return db_t{cmp, value};

    }
```

I copied this part from db_safe.hh, why am I not allowed to create an INF_VALUE bound here?

Thanks and best regards,
Schulzen

**Comment by fredher** [comment]
Hi,

This is to avoid inconsistencies that could arise from using big integer values (or very small ones), and return a value that is not the one that you expect. Use instead `tchecker::dbm::LT_INFINITY` to get (<,infinity). I hope that this answers your question.

Please, keep us inform with your projects using TChecker. This is very important and motivating for us to learn about projets involving TChecker.

Best regards,
Frédéric

**Comment by Schulzen** [comment]
Hi,

sorry for the late response and thank you for your quick answer. You can close this issue now, I will let you know if anything comes up again and keep you inform with the project using TChecker, I am working together with Alexander on this one.

Best Regards,
Schulzen
