### ISSUE TITLE
ERRORs generated while extracting certificate

### ISSUE THREAD

**Issue by mukherjee-sayan** [ticktac-project/tchecker#63]
Hi,

We are trying to generate (concrete) certificates for reachability by calling `tck-reach -a covreach -C concrete -l ...`. We sometimes are getting the following two kinds of errors (for both the errors we have `REACHABLE true`)

- `ERROR: *** compute_finite_path(symbolic): sequence is not feasible from given initial locations`
- `ERROR: clock valuation does not belong to the zone`

Could you please explain what is the meaning of these errors and when they may occur?

Best regards,
Sayan

**Comment by fredher** [comment]
Dear Sayan,
This is hard to tell what happens exactly here: it seems that TChecker has computed a symbolic counter example which is not feasible from the initial locations. This should not occur.
Could you please attach the model, and give the full command-line to let me reproduce the bug?
Best regards,
Frédéric

**Comment by mukherjee-sayan** [comment]
Dear Frédéric,

Below is a small automaton where we are getting the first error.

------------------------------------------------------

system:my_sys

event:a

clock:1:x

process:P0
location:P0:l0{initial:}
location:P0:l1{}
location:P0:l2{labels: accepting}

edge:P0:l0:l1:a{provided:x>0&&x<1}
edge:P0:l0:l1:a{provided:x>=1}
edge:P0:l1:l2:a{provided:x<1&&x>0 : do:x=0}

------------------------------------------------------

We are using the following on the command line: `tck-reach -a covreach -C concrete -l accepting <filename.txt>`
This shows that `REACHABLE true` but produces the error `ERROR: *** compute_finite_path(symbolic): sequence is not feasible from given initial locations`

We will try to find a small example where the second error was occurring.

Best regards,
Sayan

**Comment by mukherjee-sayan** [comment]
Thanks Frédéric for the quick fix. We are not facing that error anymore :)

Best regards,
Sayan
